name: Extract vendor_boot.img from URL

on:
  workflow_dispatch:
    inputs:
      vendor_boot_url:
        description: 'Direct URL to vendor_boot.img'
        required: true
        type: string

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download magiskboot (precompiled)
      run: |
        curl -L -o magiskboot https://github.com/topjohnwu/magisk/releases/latest/download/magiskboot
        chmod +x magiskboot

    - name: Download vendor_boot.img
      run: |
        curl -L -o vendor_boot.img "${{ github.event.inputs.vendor_boot_url }}"

    - name: Extract with magiskboot
      run: |
        mkdir extracted
        ./magiskboot unpack vendor_boot.img
        mv split_img extracted/ || echo "No split_img"
        mv ramdisk extracted/ || echo "No ramdisk"

    - name: Upload extracted files
      uses: actions/upload-artifact@v3
      with:
        name: vendor_boot_extracted
        path: extracted/
